# Generated by Django 3.0.6 on 2020-05-16 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='EmployeeId',
            field=models.IntegerField(),
        ),
    ]
