# Generated by Django 3.0.6 on 2020-06-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_auto_20200516_0437'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('Temperaurereading', models.CharField(max_length=20)),
                ('HumidityReading', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='EmployeeDetails',
        ),
    ]
