# Generated by Django 3.0.6 on 2020-06-24 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20200624_1006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading',
            name='HumidityReading',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='Temperaurereading',
        ),
    ]
