# Generated by Django 3.0.6 on 2020-06-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20200624_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemperatureReadings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.CharField(max_length=20)),
                ('recorded_time', models.TimeField()),
            ],
        ),
    ]
