# Generated by Django 3.0.6 on 2020-06-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_temperaturereadings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturereadings',
            name='recorded_time',
            field=models.DateTimeField(),
        ),
    ]
