# Generated by Django 3.0.6 on 2020-06-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_auto_20200624_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturereadings',
            name='recorded_time',
            field=models.CharField(max_length=100),
        ),
    ]
