# Generated by Django 3.0.6 on 2020-06-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_auto_20200624_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='HumidityReadings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidity', models.CharField(max_length=20)),
                ('recorded_time', models.CharField(max_length=100)),
            ],
        ),
    ]
