# Generated by Django 3.0.6 on 2020-06-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_humidityreadings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Humidity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidity', models.CharField(default='0', max_length=20)),
                ('recorded_time', models.CharField(max_length=100)),
                ('device_id', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.CharField(max_length=20)),
                ('recorded_time', models.CharField(max_length=100)),
                ('device_id', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='HumidityReadings',
        ),
        migrations.DeleteModel(
            name='TemperatureReadings',
        ),
        migrations.AddField(
            model_name='reading',
            name='humidity',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reading',
            name='temperature',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
