# Generated by Django 3.0.6 on 2020-06-24 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_auto_20200624_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reading',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='reading',
            name='temperature',
        ),
    ]
