# Generated by Django 3.0.6 on 2020-06-24 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_auto_20200624_1211'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reading',
            new_name='Devices',
        ),
    ]
